PROJECT_COLUMNS_MAPPING = [
    {'label': 'Project ID',
     'fieldname': 'project_id',
     'fieldtype': 'link'},
    {'label': 'Project name',
     'fieldname': 'project_name',
     'fieldtype': 'string'},
    {'label': 'Project type',
     'fieldname': 'project_type',
     'fieldtype': 'string'},
    {'label': 'Project status',
     'fieldname': 'project_status',
     'fieldtype': 'status'},
    {'label': 'Created At',
     'fieldname': 'created_at',
     'fieldtype': 'dateTime'},
    {'label': 'Last Updated',
     'fieldname': 'updated_at',
     'fieldtype': 'dateTime'},
]