# Generated by Django 5.0.6 on 2024-08-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectManager',
            fields=[
                ('project_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=25)),
                ('project_description', models.CharField(max_length=25)),
                ('project_type', models.CharField(choices=[('organization', 'Organization'), ('personal', 'Personal')], max_length=25)),
                ('project_status', models.CharField(choices=[('planning', 'Planning'), ('in-progress', 'In-Progress'), ('completed', 'Completed'), ('closed', 'Closed')], max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'project_manager',
            },
        ),
    ]
