# Generated by Django 5.0.6 on 2024-08-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmanager',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectmanager',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
