# Generated by Django 5.0.6 on 2024-08-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0002_projectmanager_end_date_projectmanager_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmanager',
            name='project_description',
            field=models.CharField(max_length=255),
        ),
    ]
