# Generated by Django 5.0.6 on 2024-08-05 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('project_manager', '0003_alter_projectmanager_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmanager',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_projects', to='authentication.userauthentication'),
        ),
    ]
