# Generated by Django 5.0.6 on 2024-08-05 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0004_projectmanager_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmanager',
            old_name='user_id',
            new_name='user',
        ),
    ]
