# Generated by Django 5.0.6 on 2024-08-05 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('project_manager', '0005_rename_user_id_projectmanager_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmanager',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_projects', to='authentication.userauthentication'),
        ),
    ]
