# Generated by Django 5.0.6 on 2024-08-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0006_alter_projectmanager_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmanager',
            name='project_status',
            field=models.CharField(choices=[('planning', 'Planning'), ('in-progress', 'In-Progress'), ('paused', 'Paused'), ('completed', 'Completed'), ('closed', 'Closed')], max_length=25),
        ),
    ]
