# Generated by Django 5.0.6 on 2024-08-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0007_alter_projectmanager_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmanager',
            name='owner',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
